#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) 2021, 2022, Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
###########################################################################

# View these jobs in the browser: https://app.circleci.com/pipelines/github/curl/curl

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  configure:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="openssl"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--enable-warnings --enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            ./configure ${COMP_ARG} --with-${SW_ED} --prefix=/home/circleci/build
            echo 'export SW_ED="openssl"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--enable-warnings --enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"
  configure-openssl-no-verbose:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="openssl"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--disable-verbose --enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            ./configure ${COMP_ARG} --with-${SW_ED} --prefix=/home/circleci/build
            echo 'export SW_ED="openssl"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--disable-verbose --enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"
  configure-no-proxy:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="openssl_noproxy"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            ./configure ${COMP_ARG} --disable-proxy --with-openssl --prefix=/home/circleci/build
            echo 'export SW_ED="openssl_noproxy"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"
  install-cares:
    steps:
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y libc-ares-dev
  install-libssh:
    steps:
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y libssh-dev
  install-deps:
    steps:
      - run:
          command: |
            sudo apt-get update && sudo apt-get install -y libpsl-dev libbrotli-dev libzstd-dev zlib1g-dev
  configure-libssh:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="openssl_libssh"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--enable-warnings --enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            ./configure ${COMP_ARG} --with-openssl --with-libssh --prefix=/home/circleci/build
            echo 'export SW_ED="openssl_libssh"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--enable-warnings --enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"
  install-wolfssl:
    steps:
      - run:
          command: |
            curl -LO https://github.com/wolfSSL/wolfssl/archive/v5.1.1-stable.tar.gz
            tar -xzf v5.1.1-stable.tar.gz
            cd wolfssl-5.1.1-stable
            ./autogen.sh
            ./configure --enable-tls13 --enable-all --enable-harden --prefix=$HOME/wssl
            make && make install
  install-wolfssh:
    steps:
      - run:
          command: |
            curl -LO https://github.com/wolfSSL/wolfssh/archive/v1.4.8-stable.tar.gz
            tar -xzf v1.4.8-stable.tar.gz
            cd wolfssh-1.4.8-stable
            ./autogen.sh
            ./configure --with-wolfssl=$HOME/wssl --prefix=$HOME/wssh --enable-scp --enable-sftp --disable-examples
            make && make install
  configure-cares:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="openssl_ares"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--enable-warnings --enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            ./configure ${COMP_ARG} --with-openssl --enable-ares --prefix=/home/circleci/build
            echo 'export SW_ED="openssl_ares"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--enable-warnings --enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"
  configure-wolfssh:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="wolfssl"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--enable-warnings --enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            LDFLAGS="-Wl,-rpath,$HOME/wssh/lib" ./configure ${COMP_ARG} --with-${SW_ED}=$HOME/wssl --with-wolfssh=$HOME/wssh --prefix=/home/circleci/build
            echo 'export SW_ED="wolfssl"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--enable-warnings --enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"
  configure-cares-debug:
    steps:
      - run:
          command: |
            ./buildconf
            SW_ED="openssl_ares"
            echo "sw_editon: ${SW_ED}"
            COMP_ARG="--enable-debug --enable-werror"
            echo "comp_arg: ${COMP_ARG}"
            ./configure ${COMP_ARG} --with-openssl --enable-ares --prefix=/home/circleci/build
            echo 'export SW_ED="openssl_ares"' >> $BASH_ENV
            echo "sw_editon: ${SW_ED}"
            echo 'export COMP_ARG="--enable-debug --enable-werror"' >> $BASH_ENV
            echo "comp_arg: ${COMP_ARG}"

  gettags:
    steps:
      - run:
          command: |
            git fetch --all --tags --prune
            git checkout tags/$TAG
            echo "my tag:" $TAG
  build:
    steps:
      - run: 
          command: |
            pwd
            make
            sudo make install
            pwd
            echo "my TAG" $TAG

  bac-deploy:
    steps:          
      - run:
          command: |
            cd ../
            git clone git@github.com:csalmon1/BAC.git
            cd BAC
            desc=""
            if [[ "$COMP_ARG" == "--disable-verbose --enable-werror" ]]
            then
              desc="noverb"
            elif [[ "$COMP_ARG" == "--enable-debug --enable-werror" ]]
            then
              desc="debug"
            elif [[ "$COMP_ARG" == "--enable-warnings --enable-werror" ]]
            then
              desc="warn"
            elif [[ "$COMP_ARG" == "--enable-werror" ]]
            then
              desc="err"
            fi
            build_config="${TAG}-${PLAT}${OS}${SW_ED}_${desc}_${COMP}"
            sudo mkdir -p ${build_config}
            echo "Directory name:" ${build_config}
            sudo mv /home/circleci/build/* ${build_config}
            git checkout -b brnch_${build_config}
            git config --global user.email "csalmon@oceanit.com"
            git config --global user.name "csalmon1"
            git add ${build_config}/*
            git commit -m "Circleci deployment ${CIRCLE_BUILD_NUM}, moving artifacts from $TAG to BAC repo [skip ci]"
            git push origin brnch_${build_config}
            echo "my TAG" ${TAG}
            echo "my SW_ED" ${SW_ED}

  aws-deploy:
    steps:          
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          arguments:
          from: /home/circleci/build/description.txt
          to: 'arn:aws-us-gov:s3:us-gov-west-1:653605740874:accesspoint/curl-bucket-access'

  setvar:
    steps:
      - run:
          command: |
            echo 'export TAG="curl-7_82_0"' >> $BASH_ENV
            echo 'export PLAT="x86"' >> $BASH_ENV
            echo 'export OS="ubuntu"' >> $BASH_ENV
            echo 'export OS_DESC="ubuntu-2004:202010-01"' >> $BASH_ENV
            echo 'export SW_ED="openssl"' >> $BASH_ENV
            echo 'export COMP_ARG="--enable-warnings --enable-werror"' >> $BASH_ENV
            echo 'export COMP="gcc"' >> $BASH_ENV
  setvar_arm:
    steps:
      - run:
          command: |
            echo 'export PLAT="ARM"' >> $BASH_ENV
            echo 'export OS_DESC="ubuntu-2004:202101-01"' >> $BASH_ENV

  verify:
    steps:
      - run:
          command: |
            echo "my tag:" $TAG
            git status
            echo "platform: ${PLAT}"
            echo "OS: ${OS}"
            echo "sw_editon: ${SW_ED}"
            echo "compiler arg: ${COMP_ARG}"
            echo "compiler: ${COMP}"

  describe:
    steps:
      - run:
          command: |
            echo "Binary Artifact Description" >> description.txt
            echo "vendor: the curl project" >> description.txt
            echo "product: libcurl" >> description.txt
            echo "version:" ${TAG} >> description.txt
            echo "target_hw: ${PLAT}" >> description.txt
            echo "target_sw: ${OS_DESC}" >> description.txt
            echo "sw_edition: ${SW_ED}" >> description.txt
            echo "compiler arg: ${COMP_ARG}" >> description.txt
            echo "compiler: ${COMP}" >> description.txt
            echo "Circleci job name:" ${CIRCLE_JOB} >> description.txt
            echo "Circleci job number:" ${CIRCLE_BUILD_NUM} >> description.txt
            sudo mv description.txt /home/circleci/build
            sudo mv config.log /home/circleci/build

  test:
    steps:
      - run: make V=1 test-ci

executors:
  ubuntu:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    
orbs:
  aws-s3: circleci/aws-s3@3.0
  win: circleci/windows@2.2.0

jobs:
  x86-openssl:
    executor: ubuntu
    steps:
      - checkout
      - setvar
      - gettags
      - verify
      - configure
      - verify
      - build
      - describe
      - bac-deploy
#      - test

  no-verbose:
    executor: ubuntu
    steps:
      - checkout
      - install-deps
      - setvar
      - gettags
      - configure-openssl-no-verbose
      - verify
      - build
      - describe
      - bac-deploy

  wolfssh:
    executor: ubuntu
    steps:
      - checkout
      - install-deps
      - install-wolfssl
      - install-wolfssh
      - setvar
      - gettags
      - verify
      - configure-wolfssh
      - verify
      - build
      - describe
      - bac-deploy

  no-proxy:
    executor: ubuntu
    steps:
      - checkout
      - install-deps
      - setvar
      - gettags
      - verify
      - configure-no-proxy
      - verify
      - build
      - describe
      - bac-deploy
#      - test

  cares:
    executor: ubuntu
    steps:
      - checkout
      - install-cares
      - setvar
      - gettags
      - verify
      - configure-cares
      - verify
      - build
      - describe
      - bac-deploy
#      - test

  libssh:
    executor: ubuntu
    steps:
      - checkout
      - install-libssh
      - setvar
      - gettags
      - verify
      - configure-libssh
      - verify
      - build
      - describe
      - bac-deploy
#      - test

  arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - setvar
      - setvar_arm
      - gettags
      - verify
      - configure
      - verify
      - build
      - describe
      - bac-deploy
#      - test

  arm-cares:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - install-cares
      - setvar
      - setvar_arm
      - gettags
      - verify
      - configure-cares-debug
      - verify
      - build
      - describe
      - bac-deploy
#      - test

workflows:
#  basic:
#    jobs:
#      - x86-openssl

#  openssl-no-verbose:
#    jobs:
#      - no-verbose

#  wolfssl-wolfssh:
#    jobs:
#      - wolfssh

  openssl-c-ares:
    jobs:
      - cares

  openssl-libssh:
    jobs:
      - libssh

  openssl-no-proxy:
    jobs:
      - no-proxy

  arm-openssl:
    jobs:
      - arm

  arm-openssl-c-ares:
    jobs:
      - arm-cares
